import type { WordInput } from './store'

export const seedWords: WordInput[] = [
  { jp: 'これ', reading: 'これ', meaning: '이것', category: '지시어', example: 'これは本です。\n이것은 책입니다.' },
  { jp: 'それ', reading: 'それ', meaning: '그것', category: '지시어', example: 'それは何ですか。\n그것은 무엇입니까?' },
  { jp: 'あれ', reading: 'あれ', meaning: '저것', category: '지시어', example: 'あれは駅です。\n저것은 역입니다.' },
  { jp: 'どれ', reading: 'どれ', meaning: '어느 것', category: '지시어', example: 'あなたの傘はどれですか。\n당신의 우산은 어느 것입니까?' },
  { jp: 'ここ', reading: 'ここ', meaning: '여기 / 이곳', category: '지시어', example: 'ここは学校です。\n여기는 학교입니다.' },
  { jp: 'そこ', reading: 'そこ', meaning: '거기 / 그곳', category: '지시어', example: 'そこに座ってください。\n거기에 앉아 주세요.' },
  { jp: 'あそこ', reading: 'あそこ', meaning: '저기 / 저곳', category: '지시어', example: 'あそこにコンビニがあります。\n저기에 편의점이 있습니다.' },
  { jp: 'どこ', reading: 'どこ', meaning: '어디', category: '지시어', example: 'トイレはどこですか。\n화장실은 어디입니까?' },
  { jp: 'この', reading: 'この', meaning: '이 ~', category: '지시어', example: 'この本は面白いです。\n이 책은 재미있습니다.' },
  { jp: 'その', reading: 'その', meaning: '그 ~', category: '지시어', example: 'その店は有名です。\n그 가게는 유명합니다.' },
  { jp: 'あの', reading: 'あの', meaning: '저 ~', category: '지시어', example: 'あの人は先生です。\n저 사람은 선생님입니다.' },
  { jp: 'どの', reading: 'どの', meaning: '어느 ~', category: '지시어', example: 'どの映画が好きですか。\n어느 영화를 좋아합니까?' },
  { jp: '食べる', reading: 'たべる', meaning: '먹다', category: '동사', polite: '食べます', example: 'ご飯を食べます。\n밥을 먹습니다.' },
  { jp: '飲む', reading: 'のむ', meaning: '마시다', category: '동사', polite: '飲みます', example: '水を飲みます。\n물을 마십니다.' },
  { jp: '見る', reading: 'みる', meaning: '보다', category: '동사', polite: '見ます', example: '映画を見ます。\n영화를 봅니다.' },
  { jp: '聞く', reading: 'きく', meaning: '듣다 / 묻다', category: '동사', polite: '聞きます', example: '音楽を聞きます。\n음악을 듣습니다.' },
  { jp: '読む', reading: 'よむ', meaning: '읽다', category: '동사', polite: '読みます', example: '本を読みます。\n책을 읽습니다.' },
  { jp: '書く', reading: 'かく', meaning: '쓰다', category: '동사', polite: '書きます', example: '名前を書きます。\n이름을 씁니다.' },
  { jp: '行く', reading: 'いく', meaning: '가다', category: '동사', polite: '行きます', example: '学校へ行きます。\n학교에 갑니다.' },
  { jp: '来る', reading: 'くる', meaning: '오다', category: '동사', polite: '来ます（きます）', example: '友達が来ます。\n친구가 옵니다.' },
  { jp: 'する', reading: 'する', meaning: '하다', category: '동사', polite: 'します', example: '勉強します。\n공부합니다.' },
  { jp: '話す', reading: 'はなす', meaning: '말하다', category: '동사', polite: '話します', example: '日本語で話します。\n일본어로 말합니다.' },
  { jp: '買う', reading: 'かう', meaning: '사다', category: '동사', polite: '買います', example: 'パンを買います。\n빵을 삽니다.' },
  { jp: '会う', reading: 'あう', meaning: '만나다', category: '동사', polite: '会います', example: '友達に会います。\n친구를 만납니다.' },
  { jp: '寝る', reading: 'ねる', meaning: '자다', category: '동사', polite: '寝ます', example: '十一時に寝ます。\n11시에 잡니다.' },
  { jp: '起きる', reading: 'おきる', meaning: '일어나다', category: '동사', polite: '起きます', example: '七時に起きます。\n7시에 일어납니다.' },
  { jp: '上', reading: 'うえ', meaning: '위', category: '위치', example: '机の上に本があります。\n책상 위에 책이 있습니다.' },
  { jp: '下', reading: 'した', meaning: '아래', category: '위치', example: '椅子の下に猫がいます。\n의자 아래에 고양이가 있습니다.' },
  { jp: '前', reading: 'まえ', meaning: '앞', category: '위치', example: '駅の前で会います。\n역 앞에서 만납니다.' },
  { jp: '後ろ', reading: 'うしろ', meaning: '뒤', category: '위치', example: '学校の後ろに公園があります。\n학교 뒤에 공원이 있습니다.' },
  { jp: '中', reading: 'なか', meaning: '안 / 속', category: '위치', example: 'かばんの中にあります。\n가방 안에 있습니다.' },
  { jp: '外', reading: 'そと', meaning: '밖', category: '위치', example: '外は寒いです。\n밖은 춥습니다.' },
  { jp: '右', reading: 'みぎ', meaning: '오른쪽', category: '위치', example: '右に曲がってください。\n오른쪽으로 돌아 주세요.' },
  { jp: '左', reading: 'ひだり', meaning: '왼쪽', category: '위치', example: '左に銀行があります。\n왼쪽에 은행이 있습니다.' },
  { jp: '隣', reading: 'となり', meaning: '옆 / 이웃', category: '위치', example: 'コンビニの隣です。\n편의점 옆입니다.' },
  { jp: '今日', reading: 'きょう', meaning: '오늘', category: '시간', example: '今日は暑いです。\n오늘은 덥습니다.' },
  { jp: '明日', reading: 'あした', meaning: '내일', category: '시간', example: '明日行きます。\n내일 갑니다.' },
  { jp: '昨日', reading: 'きのう', meaning: '어제', category: '시간', example: '昨日映画を見ました。\n어제 영화를 봤습니다.' },
  { jp: '今', reading: 'いま', meaning: '지금', category: '시간', example: '今、何時ですか。\n지금 몇 시입니까?' },
  { jp: '朝', reading: 'あさ', meaning: '아침', category: '시간', example: '朝ご飯を食べます。\n아침밥을 먹습니다.' },
  { jp: '昼', reading: 'ひる', meaning: '낮 / 점심때', category: '시간', example: '昼に会いましょう。\n점심때 만납시다.' },
  { jp: '夜', reading: 'よる', meaning: '밤', category: '시간', example: '夜に勉強します。\n밤에 공부합니다.' },
  { jp: '何', reading: 'なに／なん', meaning: '무엇 / 뭐', category: '의문사', example: 'これは何ですか。\n이것은 무엇입니까?' },
  { jp: '誰', reading: 'だれ', meaning: '누구', category: '의문사', example: 'あの人は誰ですか。\n저 사람은 누구입니까?' },
  { jp: 'いつ', reading: 'いつ', meaning: '언제', category: '의문사', example: 'いつ日本へ行きますか。\n언제 일본에 갑니까?' },
  { jp: 'なぜ', reading: 'なぜ', meaning: '왜', category: '의문사', example: 'なぜですか。\n왜입니까?' },
  { jp: 'どう', reading: 'どう', meaning: '어떻게 / 어떤 상태로', category: '의문사', example: '日本はどうですか。\n일본은 어때요?' },
  { jp: '大きい', reading: 'おおきい', meaning: '크다', category: '형용사', polite: '大きいです', example: '大きい犬です。\n큰 개입니다.' },
  { jp: '小さい', reading: 'ちいさい', meaning: '작다', category: '형용사', polite: '小さいです', example: '小さい店です。\n작은 가게입니다.' },
  { jp: '高い', reading: 'たかい', meaning: '비싸다 / 높다', category: '형용사', polite: '高いです', example: 'この時計は高いです。\n이 시계는 비쌉니다.' },
  { jp: '安い', reading: 'やすい', meaning: '싸다', category: '형용사', polite: '安いです', example: 'この店は安いです。\n이 가게는 쌉니다.' },
  { jp: '新しい', reading: 'あたらしい', meaning: '새롭다', category: '형용사', polite: '新しいです', example: '新しいスマホです。\n새 스마트폰입니다.' },
  { jp: '古い', reading: 'ふるい', meaning: '오래되다 / 낡다', category: '형용사', polite: '古いです', example: '古い家です。\n오래된 집입니다.' },
  { jp: '暑い', reading: 'あつい', meaning: '덥다 (날씨)', category: '형용사', polite: '暑いです', example: '今日は暑いです。\n오늘은 덥습니다.' },
  { jp: '寒い', reading: 'さむい', meaning: '춥다', category: '형용사', polite: '寒いです', example: '外は寒いです。\n밖은 춥습니다.' },
  { jp: 'ある', reading: 'ある', meaning: '있다 (사물)', category: '기본표현', polite: 'あります', example: '机の上に本があります。\n책상 위에 책이 있습니다.' },
  { jp: 'いる', reading: 'いる', meaning: '있다 (사람·동물)', category: '기본표현', polite: 'います', example: '部屋に猫がいます。\n방에 고양이가 있습니다.' },
  { jp: 'ない', reading: 'ない', meaning: '없다 / 아니다(부정)', category: '기본표현', polite: 'ありません／いません', example: '時間がないです。\n시간이 없습니다.' },
  { jp: '好き', reading: 'すき', meaning: '좋아하다 / 좋아함', category: '기본표현', polite: '好きです', example: '猫が好きです。\n고양이를 좋아합니다.' },
  { jp: '嫌い', reading: 'きらい', meaning: '싫어하다 / 싫어함', category: '기본표현', polite: '嫌いです', example: '雨が嫌いです。\n비를 싫어합니다.' }
]
